sonar.projectKey=cyberwatch
sonar.projectName=CyberWatch SOC
sonar.projectVersion=1.0

sonar.sources=.
sonar.host.url=http://localhost:9000

sonar.login=squ_4831daa2eb47bad919397383000c4288b06bbbc8
sonar.exclusions=venv/**,__pycache__/**,**/*.pyc
