name: SonarQube Scan

on:
  push:
    branches:
      - main

jobs:
  sonar:
    runs-on: self-hosted   # 👈 IMPORTANT (ou ubuntu-latest si Sonar est public)

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          pip install -r requirements.txt || true

      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@v2
        env:
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args: >
            -Dsonar.projectKey=cyberwatch
            -Dsonar.projectName=CyberWatch SOC
            -Dsonar.sources=.
            -Dsonar.exclusions=venv/**,__pycache__/**,**/*.pyc
